language: node_js
node_js: stable
branches:
  only:
  - hexo
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_e9f030e8d827_key -iv $encrypted_e9f030e8d827_iv
  -in ./.travis/id_rsa_blog_hexo.enc -out ~/.ssh/id_rsa_blog_hexo -d
- chmod 600 ~/.ssh/id_rsa_blog_hexo
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_blog_hexo
- cp .travis/ssh_config ~/.ssh/config
- npm install -g hexo-cli
- git clone -b mod https://github.com/foreverwang/foreverwang.github.io.git themes/next
install:
- npm install
script:
- hexo generate
after_success:
- git config --global user.name "yongheng"
- git config --global user.email "yongheng.abc@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
- hexo deploy
